// Nutrition Tracker — Food Database (~120 items)
//
// Scoring guidelines (USDA FoodData Central, Dietary Guidelines ages 4-13):
//   Protein : 0 = <2 g, 1 = 2-7 g, 2 = 8-15 g, 3 = 16 g+
//   Veggie  : 0 = <1 g no veggie, 1 = 1-2 g or partial, 2 = 2-4 g or full serving, 3 = 4 g+ vegetable-forward
//   Sugar   : 0 = <2 g added, 1 = 2-6 g, 2 = 7-15 g, 3 = 16 g+
//   Water   : 0 = negligible, 1 = some moisture, 2 = high water, 3 = primarily hydrating
//   Vitamin : 0 = minimal, 1 = 1-2 notable, 2 = good variety, 3 = micronutrient-dense

import type { MealCategory } from './types';

export interface FoodSeedItem {
  name: string;
  emoji: string;
  meal_categories: MealCategory[];
  protein_score: number;
  veggie_score: number;
  sugar_score: number;
  water_score: number;
  vitamin_score: number;
}

export const FOOD_DATABASE: FoodSeedItem[] = [
  // =========================================================================
  // BREAKFAST (~26)
  // =========================================================================
  {
    name: 'Pancakes',
    emoji: '\u{1F95E}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Waffles',
    emoji: '\u{1F9C7}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'French Toast',
    emoji: '\u{1F35E}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Scrambled Eggs',
    emoji: '\u{1F373}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Fried Egg',
    emoji: '\u{1F373}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 2,
  },
  {
    name: 'Oatmeal',
    emoji: '\u{1F35C}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Sugary Cereal',
    emoji: '\u{1F963}',
    meal_categories: ['breakfast'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Healthy Cereal',
    emoji: '\u{1F963}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 2,
  },
  {
    name: 'Toast',
    emoji: '\u{1F35E}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Bagel',
    emoji: '\u{1F96F}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Bagel & Cream Cheese',
    emoji: '\u{1F96F}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Muffin',
    emoji: '\u{1F9C1}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Yogurt',
    emoji: '\u{1F95B}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Yogurt Parfait',
    emoji: '\u{1F366}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 2,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Breakfast Burrito',
    emoji: '\u{1F32F}',
    meal_categories: ['breakfast'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Bacon',
    emoji: '\u{1F953}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Sausage',
    emoji: '\u{1F32D}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Hash Browns',
    emoji: '\u{1F954}',
    meal_categories: ['breakfast'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Fruit Salad',
    emoji: '\u{1F353}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 0,
    veggie_score: 2,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Banana',
    emoji: '\u{1F34C}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Smoothie Bowl',
    emoji: '\u{1F963}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Granola Bar',
    emoji: '\u{1F36B}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Pop-Tart',
    emoji: '\u{1F36A}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Donut',
    emoji: '\u{1F369}',
    meal_categories: ['breakfast', 'snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Acai Bowl',
    emoji: '\u{1FAD0}',
    meal_categories: ['breakfast'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Overnight Oats',
    emoji: '\u{1F95B}',
    meal_categories: ['breakfast'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 2,
  },

  // =========================================================================
  // LUNCH (~25)
  // =========================================================================
  {
    name: 'PB&J',
    emoji: '\u{1F96A}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Grilled Cheese',
    emoji: '\u{1F9C0}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Turkey Sandwich',
    emoji: '\u{1F96A}',
    meal_categories: ['lunch'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Ham Sandwich',
    emoji: '\u{1F96A}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Chicken Nuggets',
    emoji: '\u{1F357}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Mac & Cheese',
    emoji: '\u{1F9C0}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Cheese Pizza',
    emoji: '\u{1F355}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Pepperoni Pizza',
    emoji: '\u{1F355}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Hot Dog',
    emoji: '\u{1F32D}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Burger',
    emoji: '\u{1F354}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Quesadilla',
    emoji: '\u{1FAD4}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Wrap',
    emoji: '\u{1F32F}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Soup',
    emoji: '\u{1F372}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 2,
  },
  {
    name: 'Salad',
    emoji: '\u{1F957}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 1,
    veggie_score: 3,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Pasta with Sauce',
    emoji: '\u{1F35D}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Rice & Beans',
    emoji: '\u{1F35A}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Fish Sticks',
    emoji: '\u{1F41F}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Sushi Roll',
    emoji: '\u{1F363}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Hummus & Pita',
    emoji: '\u{1FAD8}',
    meal_categories: ['lunch', 'snack'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Lunchable',
    emoji: '\u{1F4E6}',
    meal_categories: ['lunch'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Corn Dog',
    emoji: '\u{1F32D}',
    meal_categories: ['lunch'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Taco',
    emoji: '\u{1F32E}',
    meal_categories: ['lunch', 'dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'BLT',
    emoji: '\u{1F96A}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Chicken Salad',
    emoji: '\u{1F957}',
    meal_categories: ['lunch'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Sub Sandwich',
    emoji: '\u{1F96A}',
    meal_categories: ['lunch'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },

  // =========================================================================
  // DINNER (~25)
  // =========================================================================
  {
    name: 'Chicken Breast',
    emoji: '\u{1F357}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Steak',
    emoji: '\u{1F969}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Salmon',
    emoji: '\u{1F41F}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 3,
  },
  {
    name: 'Pork Chop',
    emoji: '\u{1F356}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Meatballs',
    emoji: '\u{1F9C6}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Pasta & Meatballs',
    emoji: '\u{1F35D}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Stir Fry',
    emoji: '\u{1F958}',
    meal_categories: ['dinner'],
    protein_score: 2,
    veggie_score: 3,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Fried Rice',
    emoji: '\u{1F35A}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Roast Chicken',
    emoji: '\u{1F357}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Tacos',
    emoji: '\u{1F32E}',
    meal_categories: ['dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Burrito',
    emoji: '\u{1F32F}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Lasagna',
    emoji: '\u{1F35D}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Casserole',
    emoji: '\u{1F372}',
    meal_categories: ['dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Roasted Veggies',
    emoji: '\u{1F955}',
    meal_categories: ['dinner'],
    protein_score: 0,
    veggie_score: 3,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 3,
  },
  {
    name: 'Mashed Potatoes',
    emoji: '\u{1F954}',
    meal_categories: ['dinner'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Corn on the Cob',
    emoji: '\u{1F33D}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Broccoli',
    emoji: '\u{1F966}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 3,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Green Beans',
    emoji: '\u{1FAD8}',
    meal_categories: ['dinner'],
    protein_score: 0,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Rice',
    emoji: '\u{1F35A}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 0,
  },
  {
    name: 'Bread Roll',
    emoji: '\u{1F35E}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Baked Potato',
    emoji: '\u{1F954}',
    meal_categories: ['dinner'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },
  {
    name: 'Curry',
    emoji: '\u{1F35B}',
    meal_categories: ['dinner'],
    protein_score: 2,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Ramen',
    emoji: '\u{1F35C}',
    meal_categories: ['dinner'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 1,
  },
  {
    name: 'Ribs',
    emoji: '\u{1F356}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Grilled Shrimp',
    emoji: '\u{1F990}',
    meal_categories: ['dinner'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 1,
    vitamin_score: 2,
  },

  // =========================================================================
  // SNACKS & DESSERTS (~25)
  // =========================================================================
  {
    name: 'Apple',
    emoji: '\u{1F34E}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 2,
  },
  // Note: Banana already defined in breakfast+snack above
  {
    name: 'Grapes',
    emoji: '\u{1F347}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Strawberries',
    emoji: '\u{1F353}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Orange',
    emoji: '\u{1F34A}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Carrots & Ranch',
    emoji: '\u{1F955}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Celery & PB',
    emoji: '\u{1FAD2}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 0,
    water_score: 2,
    vitamin_score: 1,
  },
  {
    name: 'Cheese Stick',
    emoji: '\u{1F9C0}',
    meal_categories: ['snack'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Crackers',
    emoji: '\u{1F9C7}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Goldfish',
    emoji: '\u{1F41F}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Pretzels',
    emoji: '\u{1F968}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Trail Mix',
    emoji: '\u{1F95C}',
    meal_categories: ['snack'],
    protein_score: 2,
    veggie_score: 1,
    sugar_score: 1,
    water_score: 0,
    vitamin_score: 2,
  },
  {
    name: 'Popcorn',
    emoji: '\u{1F37F}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 1,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Chips',
    emoji: '\u{1F35F}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Cookies',
    emoji: '\u{1F36A}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Ice Cream',
    emoji: '\u{1F368}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Candy',
    emoji: '\u{1F36C}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Brownie',
    emoji: '\u{1F36B}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Cupcake',
    emoji: '\u{1F9C1}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Fruit Snacks',
    emoji: '\u{1F353}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 1,
  },
  {
    name: 'Rice Krispie Treat',
    emoji: '\u{1F370}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 0,
    vitamin_score: 0,
  },
  {
    name: 'Popsicle',
    emoji: '\u{1F366}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 1,
    vitamin_score: 0,
  },
  {
    name: 'Pudding',
    emoji: '\u{1F36E}',
    meal_categories: ['snack'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Jello',
    emoji: '\u{1F36E}',
    meal_categories: ['snack'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 1,
    vitamin_score: 0,
  },
  // Note: Granola Bar already defined in breakfast+snack above

  // =========================================================================
  // DRINKS (~20)
  // =========================================================================
  {
    name: 'Water',
    emoji: '\u{1F4A7}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 0,
  },
  {
    name: 'Milk',
    emoji: '\u{1F95B}',
    meal_categories: ['drink'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Chocolate Milk',
    emoji: '\u{1F95B}',
    meal_categories: ['drink'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Orange Juice',
    emoji: '\u{1F34A}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Apple Juice',
    emoji: '\u{1F34E}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 1,
  },
  {
    name: 'Lemonade',
    emoji: '\u{1F34B}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 1,
  },
  {
    name: 'Smoothie',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 1,
    veggie_score: 2,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 3,
  },
  {
    name: 'Sports Drink',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 0,
  },
  {
    name: 'Soda',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 1,
    vitamin_score: 0,
  },
  {
    name: 'Hot Chocolate',
    emoji: '\u2615',
    meal_categories: ['drink'],
    protein_score: 1,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 1,
  },
  {
    name: 'Iced Tea',
    emoji: '\u{1F375}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 0,
  },
  {
    name: 'Sparkling Water',
    emoji: '\u{1FAD7}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 0,
  },
  {
    name: 'Coconut Water',
    emoji: '\u{1F965}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 3,
    vitamin_score: 2,
  },
  {
    name: 'Milkshake',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 1,
    vitamin_score: 1,
  },
  {
    name: 'Juice Box',
    emoji: '\u{1F9C3}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 2,
    vitamin_score: 1,
  },
  {
    name: 'Capri Sun',
    emoji: '\u{1F9C3}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 2,
    water_score: 1,
    vitamin_score: 0,
  },
  {
    name: 'Protein Shake',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 3,
    veggie_score: 0,
    sugar_score: 1,
    water_score: 2,
    vitamin_score: 2,
  },
  {
    name: 'Herbal Tea',
    emoji: '\u{1F375}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 1,
  },
  {
    name: 'Lemon Water',
    emoji: '\u{1F34B}',
    meal_categories: ['drink'],
    protein_score: 0,
    veggie_score: 0,
    sugar_score: 0,
    water_score: 3,
    vitamin_score: 1,
  },
  {
    name: 'Chocolate Shake',
    emoji: '\u{1F964}',
    meal_categories: ['drink'],
    protein_score: 2,
    veggie_score: 0,
    sugar_score: 3,
    water_score: 1,
    vitamin_score: 1,
  },
];
